name: Scheduled Build
on:
  workflow_dispatch:
  schedule:
    - cron:  '* */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-
        curl "http://data.fixer.io/api/latest?access_key=$API_KEY" | jq . > latest-forex.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
